nuxt-modules/sanity

docs/content/settings.json

The logo is broken when you want to go directly to a subpage.
Example: https://sanity.nuxtjs.org/quick-start/

docs: fix logo path

---

docs/content/en/helpers/images.md

A small PR. closes #20
maybe we could also add a short paragraph about the cases someone would use `@sanity/client` over `SanityImage`. I haven't really use `SanityImage` yet, but I'm planning to so for an upcoming project, so I'll have more to say about this.
In the example, I thought I might as well show some best practices (alt text, [setting width and height](https://www.youtube.com/watch?v=4-d_SoCHeWE&feature=youtu.be), lazy loading) 😋

docs: add example with `@sanity/image-url`

---

src/components/sanity-image.ts

I was trying to change quality of image, but `q` was missing on keys map.

fix: correctly use `q` prop in `<SanityImage>`

---

docs/content/en/usage.md

Hey again!
I added an example of fetching data inside the `asyncData` hook, using a ["shorthand" pattern](https://deploy-preview-60--nuxt-sanity-module.netlify.app/usage#example-with-asyncdata). @vicbergquist used it [in her documentation](https://nuxt-sanity.netlify.app/usage/#in-asyncdata) and I liked how concise the code was. No need for `async/await` keywords or `then()` methods.
Showing both JS and TS variants at the same time ruined a bit the concision that I wanted to showcase. That's why I used the code-block component.

docs: add asyncData `fetch` example

---

docs/content/settings.json

closes #91 
also fixes the "edit this page" link.
It took me a moment to find the configuration (https://docus.dev/get-started/configuration) and some more time to realize that `Docus` has yet to be announced 😆

docs: add back link to GitHub in header

---

docs/pages/en/1.getting-started/3.usage.md

Teeny tiny change to fix an issue that was causing one of the Usage code blocks to render incorrectly. Probably caused by copy/pasting code after a redesign or something similar.
- broken: https://sanity.nuxtjs.org/getting-started/usage#example-with-fetch
- fixed: https://deploy-preview-180--nuxt-sanity-module.netlify.app/getting-started/usage#example-with-fetch

Fix broken code block

---

package.json

ERROR  (node:69269) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Volumes/Dane/Repozytoria/osklad.pl/node_modules/@nuxtjs/sanity/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
Node: v16.11.1
NPM: 8.0.0
It is compatible with Node v12 as this state: https://github.com/postcss/postcss/issues/1455#issuecomment-722502548

chore: Fix DEP0148 warning message

---

src/module.ts

In the [docs ](https://sanity.nuxtjs.org/getting-started/configuration) for this module its says that you can also pass options through nuxt runtime configuration. This works as intended except when the proejctId is only specified in the runtime config. The config is [validated ](https://github.com/nuxt-community/sanity-module/blob/ee743c5687ace2bd5f8de40e0ad4049a9514aba0/src/module.ts#L88)bevor it is [merged ](https://github.com/nuxt-community/sanity-module/blob/ee743c5687ace2bd5f8de40e0ad4049a9514aba0/src/module.ts#L104)with option specified in the runtime config. Therefore, when the projectId is specified only in the runtime config the config is deemed invalid and the module won’t be initialized.
This problem could be solved if the options specified in runtime config are merged into …

fix: add sanity options from runtimeconfig to module defaults

---

docs/pages/en/2.helpers/2.images.md

according to https://github.com/sanity-io/image-url#usage, one needs to add `url()` to function.
in my limited testing, this appeared to be true

docs: add missing `.url()` call

---

src/runtime/components/sanity-content.ts
test/unit/__snapshots__/sanity-content.test.ts.snap
test/unit/fixture/portable-text/index.ts
test/unit/fixture/portable-text/text-with-props.ts
test/unit/sanity-content.test.ts

I needed props passed down to my Styles elements and Styles serializers (e.g. p, h2, h3, h4, blockquote, etc.) so I've tweaked this in Sanity Content.
Example use case - previously the below blocks would not render a `class="hello-world"` on `<blockquote />`
```
const blocks = [
{
_key: '03ed74fca82b',
_type: 'block',
class: 'hello-world',
children: [],
markDefs: [],
style: 'blockquote'
}
]
<blockquote class="hello-world"></blockquote>
```
I largely copied the code for the existing render() function, only tweak being to filter out markDefs from props.
markDefs aren't required or passed down to the Element - if we wanted to change this, this code could be used:
```
const props = Object.fromEntries(Object.entries(item).filter(([key]) => key !== '_type').map(
([key, value]) => {
if (key === …
```

fix: pass props down to styles

---

docs/content/1.getting-started/1.quick-start.md
docs/content/1.getting-started/2.configuration.md

It is no longer necessary to explicitly import `defineNuxtConfig`. Also, the Nuxt config-file is now `.ts` by default.

docs: update nuxt config examples

---

src/runtime/client.ts

For large queries, a POST request is used, but the global request options (e.g. auth token) are not added in this case. If the dataset requires authentication, this causes `useSanityQuery()` to break after a certain query size is reached.

fix: use `fetchOptions` in POST requests

---

src/runtime/composables.ts

I believe the intended behavior was to use a hash as the async data key. However, `objectHash()`, only serializes the data and includes the complete query and params. This changes it to use the hashing algorithm in ohash for a short identifier.

fix: use hash for `useAsyncData` key

---

docs/content/1.getting-started/3.usage.md

Updated the link to the `useAsyncData` documentation in the `useSanityQuery` [section](https://sanity.nuxtjs.org/getting-started/usage#usesanityquery) as it led to a `404`.
New location: https://nuxt.com/docs/getting-started/data-fetching#useasyncdata

docs: update link to `useAsyncData` documentation

---

src/runtime/client.ts

This solves #909 and fixes the same [bug](https://github.com/rexxars/picosanity/issues/22) as on [picosanity](https://github.com/rexxars/picosanity) where POSTed queries with a perspective return a 400 error.
**Note on current test setup**: The error is returned from a Sanity server receiving the request. Therefore your current test setup can not detect this error because the `$fetch` function is mocked.
Should we think about refactoring client tests to not mock the `$fetch`?

fix: send `perspective` as query param when using POST method

---

index.d.ts
playground/app.vue
playground/components/PreviewModeBanner.vue
src/module.ts
src/runtime/composables/_internal.ts
src/runtime/composables/visual-editing.ts
src/runtime/plugins/visual-editing.client.ts
src/runtime/plugins/visual-editing.server.ts
src/runtime/server/routes/proxy.ts

This PR adds a few things based on some initial feedback:
- 3fc4791 adds a `visualEditing` property to `SanityHelper` (if visual editing is enabled). The value of this property is an object with two helpers for determining the visual editing context: whether or not visual editing is enabled, and if the app is currently in a frame, i.e. in Presentation. See the playground `PreviewModeBanner.vue` component for how these might be used.
- 1e65afc fixes the missing preview mode check on the client.
- f5ad5e4 fixes the redirect parameter not being respected when disabling preview mode.
LMK if I should split these up into separate PRs.
resolves https://github.com/nuxt-modules/sanity/issues/969

feat: add preview mode helpers and checks

---

src/runtime/composables/visual-editing.ts

When consuming the module externally, I see:
`ReferenceError: useState is not defined at useSanityVisualEditingState`
Assuming this is due to a missing import.

fix: add missing `useState` import

---

docs/content/1.getting-started/3.usage.md

There is a description of using types in the vue-sanity docs, but not the nuxt ones. Not sure how you would infer type so i have not added that

Add types to docs

---

src/module.ts
src/runtime/components/sanity-content.ts
src/runtime/minimal-client.ts
src/runtime/server/routes/preview/enable.ts

This is a very early PR to make this module compatible with [changes we expect to release in Nuxt v5](https://github.com/nuxt/nuxt/issues/25323).

fix: opt in to `import.meta.*` properties

---

src/module.ts

In `get-it` [v8.4.24](https://github.com/sanity-io/get-it/blob/main/CHANGELOG.md#8424-2024-04-17) we started inlining `parse-headers` and `debug` as it were causing issues with the latest version of `hydrogen`.
The same is true for `@sanity/core-loader` [v1.6.7](https://github.com/sanity-io/visual-editing/blob/main/packages/core-loader/CHANGELOG.md#167-2024-04-17) and `async-cache-dedupe`.
What's the reason for inlining `@sanity/client` btw? It should be [strictly ESM compatible](https://publint.dev/@sanity/client@6.15.20) in its latest version 🤔

fix: `parse-headers`, `debug` and `async-cache-dedupe` no longer need to be optimized

---

pnpm-lock.yaml
src/module.ts
src/runtime/composables/visual-editing.ts

As raised in https://github.com/nuxt-modules/sanity/issues/1007, I believe @jesperbjerke is correct in his assumption that stega should be disabled (and CSM should not be delivered) if visual editing is disabled. Looks like an oversight on my part.
This PR just adds some additional checks, chiefly to modify the client config and set `stega: false` if visual editing is not enabled.

fix: enable stega only when visual editing is enabled

---

src/runtime/minimal-client.ts
test/unit/client.test.ts

This is the same issue as here: https://github.com/nuxt-modules/sanity/pull/930 but with GET queries. This appends perspective there as well.

fix: send perspective as query param when using GET method

---

docs/content/2.helpers/5.visual-editing.md
src/module.ts

#1043 which was created from this question https://github.com/nuxt-modules/sanity/issues/1007#issuecomment-2285692749
Exposes the `createDataAttribute` utility function exported by `@sanity/visual-editing` as an auto-import for the manual creation of content mappings, and adds a new page to the docs.
The function is aliased as `createSanityDataAttribute` to follow the pattern of the other auto-imports exposed by this module.
See the [Sanity docs](https://www.sanity.io/docs/visual-editing-overlays#cb95b19a0263) for more information about `createDataAttribute`.

feat: expose `createSanityDataAttribute` utility

---

src/runtime/composables/visual-editing.ts

`useSanityQuery()` accepts params which are refs or reactive. When enabling Visual Editing, the fetcher throws an error after trying to pass the params through `postMessage()` (refs are unable to be serialized).
This PR sends a properly cloned plain object to core-loader and also watches the params to re-create the fetcher with new values when changed.

fix: allow reactive params in visual editing mode

---

src/runtime/composables/visual-editing.ts

resolves https://github.com/nuxt-modules/sanity/issues/1114
This fixes a regression with the recent `@nuxtjs/sanity@1.13.2` changes which causes an error when we try to use the visual editor and we use `useSanityQuery` without passing in the second argument (the query params object)
e.g
```ts
const { data: movies, encodeDataAttribute } = await useSanityQuery<QueryResult[]>(query)
```
```
500
"undefined" is not valid JSON
at JSON.parse ()
at setupFetcher (http://localhost:3000/_nuxt/@fs/home/crazypanda/workspaces/nuxt-sanity-visual-editor-example/node_modules/@nuxtjs/sanity/dist/runtime/composables/visual-editing.js?v=ccddcf37:125:14)
at useSanityQuery (http://localhost:3000/_nuxt/@fs/home/crazypanda/workspaces/nuxt-sanity-visual-editor-example/node_modules/@nuxtjs/sanity/dist/runtime/compo …
```

fix: showing visual editor

---

package.json
pnpm-lock.yaml

This drops support for usage within CJS - which has never been needed by Nuxt v3.

build: update to latest module-builder and drop `cjs` support

---

src/runtime/components/sanity-image.ts

resolves https://github.com/nuxt-modules/sanity/issues/1226
See https://github.com/nuxt-modules/sanity/issues/1226

Update sanity-image.ts: mark as deprecated props maxH, minH, maxW & minW
